### ISSUE TITLE
List, delete, and create branches

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#137]
We want a page similar to github (https://github.com/dolthub/ld/branches) were you can view all branches (would be cool to show associated pull requests as well), delete branches, and create new branches.

To get to this page, we can maybe just make this a link and render the list under the database tab
<img width="727" alt="Screen Shot 2022-01-18 at 10 07 53 AM" src="https://user-images.githubusercontent.com/29443194/149993994-c900f94e-e394-4acf-823e-3473c60c512a.png">

The RPCs for list branches and delete branch already exist. List branches is used for that branch dropdown and right now delete branch is only used in merged pull requests

**Comment by druvv** [comment]
# Dolthub branches view

## How to access the view
Add a link in the dropdown list where you see all branches similar to github:
![Screen Shot 2022-01-18 at 11 13 01 AM](https://user-images.githubusercontent.com/14025711/150003925-8fbdad3c-ad96-4381-ac4f-8bd1d889837b.png)

When there are no branches other than main, instead of `No options`, show a link to create a new branch that takes you to the branches view and shows the branch creation flow.
![Group 1](https://user-images.githubusercontent.com/14025711/150008045-b092dafd-9376-42ce-953b-52ae5fa978c9.png)



When there is at-least one branch, show a footer that contains a link to view the Branches page.
![Branch dropdown](https://user-images.githubusercontent.com/14025711/150007364-6ff59834-17fa-4db2-b7cf-5cf0697ccc99.png)

**Comment by druvv** [comment]
# Data fetching

## Listing branches in table
Will use existing `branchNames` graphql query.

**Comment by timsehn** [comment]
This is done right @druvv?

**Comment by druvv** [comment]
shipped indeed
