### ISSUE TITLE
Pull Request UI doesn't help users enough with viewing conflicts

### ISSUE THREAD

**Issue by fulghum** [dolthub/dolthub-issues#192]
When merging a pull request from one branch to another that has a conflict, the UI doesn't make the conflict easy for customers to understand. 

For example:
* on the `main` branch, I create table t `(i int, c text)` and insert values `(1, "blue")` and commit
* then I create a `feature1` branch and insert values `(2, "green")` and commit
* back on the `main` branch, I insert values `(2, "red")` and commit

When I create a pull request from `feature1` to `main`, I would expect to see:
* that there is a data conflict that cannot be merged and will need to be resolved; instead the UI says the pull request can be merged
* a diff of the conflict showing the data in each branch; instead I just see the cumulative changes from the `feature1` branch

It's only when I hit the merge button do I see that there actually is a conflict between the two branches, and at that point it's difficult for customers to know how to proceed. It is an unwelcome surprise for customers to see that a change is "ready to merge", then to get blocked as soon as they hit the merge button. 

When I clicked the `Toggle Merge Instructions` button, I was shown steps on how to merge a conflict from the CLI. It would be helpful to proactively instruct users what to do next as soon as we know there is a merge conflict (e.g. instead of making them figure out they need to toggle the merge instructions to find out how to move forward).  It might even be worth ramping up the language a little bit to be explicit that merge conflicts cannot be resolved from the DoltHub UI and customers need to use the CLI. 

I'm wondering if the diff we show on pull requests is the cumulative diff of all changes on the branch, and not actually the diff of the tip of `feature1` to the tip of `main`. 

My idea experience would be that as soon as I open the PR page, I am told there is a conflict, I can see the diff causing the conflict easily, and I am presented with the instructions on needing to resolve and merge from the CLI.

**Comment by tbantle22** [comment]
Okay so I think this can be split up into a few different concerns:
1. If a PR has a conflict it should say so right away instead of saying "Ready to merge"
2. If there is a conflict, the language should be clearer that it can only be resolved using Dolt and the directions should be toggled open initially
3. The diff is showing cumulative changes instead of the diff of the tip of `feature1` to tip of `main`

Here's my plan:
1. Dolt does not currently support a way to know if a pull request has a conflict before attempting a merge. This is something we should support eventually, but is not a trivial fix. I made another issue [here](https://github.com/dolthub/dolthub-issues/issues/193) to follow along. In the meantime, I will make it clearer before trying to merge that it's still possible to have a conflict.
2. I will get this done this week
3. I believe the diff is showing the correct thing. Like GitHub, pull request should show the diff from the common ancestor to the tip of `feature1`. Which means it is not necessarily tip of `main` to tip of `feature1` because that would end up also including new changes to `main` and not just what has changed from `feature1`.

**Comment by fulghum** [comment]
Great plan Taylor. Thank you for digging into this one. 

You are right about the diff. [Here are GitHub docs that explain GitHub's behavior](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-comparing-branches-in-pull-requests#three-dot-and-two-dot-git-diff-comparisons). It's a two-dot diff by default, so people can see the changes they have applied, that will be merged into the receiving branch. I think the lack of seeing info on the conflict threw me and the customer off, thinking that it should be visible in the diff. Thanks for verifying that it's working as intended. 

The text updates for how to deal with conflicts and setting expectations that conflicts haven't been checked yet will be good short term changes to help customers.

**Comment by tbantle22** [comment]
I think it's three-dot by default? Yeah would be cool if you could see conflicts right away. Would be helpful

Added some clearer messaging to pull requests surrounding conflicts. The resolve conflicts directions show up by default now instead of needing to click the toggle button
![](https://cdn.discordapp.com/attachments/942839765223481484/958499958603006002/Screen_Shot_2022-03-29_at_3.29.37_PM.png)
![](https://cdn.discordapp.com/attachments/942839765223481484/958500092753621022/Screen_Shot_2022-03-29_at_3.56.43_PM.png)

**Comment by tbantle22** [comment]
UI is a little clearer now. Closing this issue in favor of https://github.com/dolthub/dolthub-issues/issues/193
