### ISSUE TITLE
Inline diff comments

### ISSUE THREAD

**Issue by tbantle22** [dolthub/dolthub-issues#251]
Similar to how you can comment on a particular line in github PRs

**Comment by g-sando** [comment]
Our users would find this extremely useful as well, for faster and more complex oversight of large PR reviews.

**Comment by timsehn** [comment]
Another customer just asked for this. This pops to the head of the queue.

**Comment by timsehn** [comment]
Customer asks for the following features as well:

1. @user-handle tagging. This is really important because it allows inline requests to be routed to a specific persons e-mail inbox.
2. “Conversations”. Multiple comments on the same line in Github are threaded into a single conversation.
3. “Resolve conversations”. Large PRs will receive lots of comments so it will be important to be able to see which ones have not been addressed yet.
4. “Outdated conversations”. If a line with comments gets updated, Github marks that conversation as outdated on the main comment stream.

**Comment by liuliu-dev** [comment]
hey @g-sando , `inline diff comments` is now in production, here is a [blog](https://www.dolthub.com/blog/2023-10-16-pull-request-diff-comments/) about it, thanks for the feature request.

**Comment by g-sando** [comment]
thanks very much for following this up @liuliu-dev, will make a big difference!
