### ISSUE TITLE
Undo hidden column in table explorer

### ISSUE THREAD

**Issue by radao** [dolthub/dolthub-issues#410]
**Is your feature request related to a problem? Please describe.**

After hiding a column in the table explorer view, theres no option to add it back. Refreshing the page does not bring it back, only navigating away from the page and going back does.

<img width="838" alt="Screen Shot 2023-02-01 at 17 20 28" src="https://user-images.githubusercontent.com/2007531/216101208-266a2788-8f0c-4459-b984-ed066362d9ac.png">

**Describe the solution you'd like**

A button to add a hidden column back.

**Describe alternatives you've considered**

**Additional context**

**Comment by liuliu-dev** [comment]
Hi @radao, thanks for the feature request.

Since those data are from query results, the best way I can think of to get a specific column back is by modifying the `select` query.

I added a button that would bring back all hidden columns:

![Screen Shot 2023-02-02 at 11 51 33 AM](https://user-images.githubusercontent.com/6688812/216436270-14caf3b2-f351-420f-b1cd-c03628a8a089.png)
